version: "2.0"

services:
  node:
    image: rzanei/sentinelhub_v12.0.0:v12.0.1
    pull_policy: always
    env:
      - GENESIS_URL=https://snapshots.polkachu.com/genesis/sentinel/genesis.json
      - PERSISTENT_PEERS=c773ecc4fce799d3064b45cf6a9a13b28aaefa3d@88.205.101.202:26656,9e108fb71ce0749e9d874595bb8560d267c69789@35.228.251.58:26656,7a608cf632825669b69801f3b9917d660eab556c@185.148.1.181:26656,2b1ecb22f9c0da6e241075cf0e8f248d2e01e637@217.154.22.215:26656,c4dcd639a38688fb20b0c122eed5fb0cad02678a@217.154.22.215:26656,c9ce449ce1cbdbf857a30c3a88539ba63e7d29e8@151.115.88.82:26656
    expose:
      - port: 26657
        as: 26657
        to:
          - global: true
      - port: 26656
        as: 26656
        to:
          - global: true
    params:
      storage:
        data:
          mount: /root/.sentinelhub

profiles:
  compute:
    node:
      resources:
        cpu:
          units: 4
        memory:
          size: 16Gi
        storage:
          - size: 10Gi
          - name: data
            size: 200Gi
            attributes:
              persistent: true
              class: beta3

  placement:
    dcloud:
      attributes:
        host: akash
        organization: europlots
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
      pricing:
        node:
          denom: uakt
          amount: 99

deployment:
  node:
    dcloud:
      profile: node
      count: 1