version: "2.0"

services:
  node:
    image: rzanei/sentinelhub_v0.11.5:v0.11.5-rc0
    expose:
      - port: 26657
        to:
          - global: true
      - port: 26656
        to:
          - global: true
    params:
      storage:
        data:
          mount: /root/.sentinelhub

profiles:
  compute:
    node:
      resources:
        cpu:
          units: 8
        memory:
          size: 64Gi
        storage:
          - size: 10Gi
          - name: data
            size: 400Gi
            attributes:
              persistent: true
              class: beta3

  placement:
    dcloud:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63
      pricing:
        node:
          denom: uakt
          amount: 500

deployment:
  node:
    dcloud:
      profile: node
      count: 1
